### ISSUE TITLE
Static interface property causes error in TypeSupport 

### ISSUE THREAD

**Issue by SBFrancies** [replaysMike/AnySerializer#19]
I have encountered a bug when trying to serialize a class which implements an interface with a static property with the type of the same interface. See the following example code:

```
public interface IExample
{
}

 public class Implementation : IExample
 {
    public static IExample Instance { get; } = new Implementation();
}

public class Program
{
    public static void Main(string[] args)
    {
        Implementation i = new Implementation();
        var bytes = i.Serialize();
    }
}
```

The exception which is thrown is comes from:

```
public static ExtendedProperty GetExtendedProperty(this Type type, string name, Type declaringType)
{
    var properties = type.GetProperties(BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.Instance);
    return properties.Single(x => x.Name.Equals(name) && x.DeclaringType.Equals(declaringType));
}
```

in type support. The Single call fails. This can be fixed by adding the Static BindingFlag when population the properties collection but I don't know what knock on effects this might cause.

**Comment by replaysMike** [comment]
Apologies for the lengthy delay, I finally got around to fixing this. It is now fixed as of version 1.1.39
