### ISSUE TITLE
ConcurrentDictionary not supported

### ISSUE THREAD

**Issue by kyrikon** [replaysMike/AnySerializer#4]
![image](https://user-images.githubusercontent.com/45612735/49483969-36e33980-f885-11e8-9b6d-058c6ab47a05.png)

**Comment by replaysMike** [comment]
I’ll take a look at this right away, should be fixed in a few hours thanks!

**Comment by replaysMike** [comment]
@kyrikon this is now supported as of version 1.0.25. I'll add support for other concurrent types in another PR.
