### ISSUE TITLE
Error while trying to serialize -  System.InvalidOperationException: Unsupported type: System.Xml.Linq.XHashtable`1

### ISSUE THREAD

**Issue by ameetj85** [replaysMike/AnySerializer#8]
One of the objects that I am trying to serialize contains some xml stuff in it. I see the following errror in my event viewer:
System.InvalidOperationException: [.<ResolvedPrincipalPreferenceInstance>k__BackingField.<DataXml>k__BackingField.lastAttr.name.ns.names.state.entries] Unsupported type: System.Xml.Linq.XHashtable`1+XHashtableState+Entry[[System.Xml.Linq.XName, System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]] ---> System.InvalidOperationException: Unsupported type: System.Xml.Linq.XHashtable`1+XHashtableState+Entry[[System.Xml.Linq.XName, System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]]
   at AnySerializer.TypeUtil.GetTypeId(ExtendedType typeSupport)
   at AnySerializer.TypeWriter.WriteObject(BinaryWriter writer, Object obj, ExtendedType typeSupport, Int32 currentDepth, String path)
Is there a workaroudn for this?

**Comment by replaysMike** [comment]
Just got back from vacation, I will take a look at what's going on here.

I presume you are using a relatively late version, can you post a code example of how you're using it?

**Comment by replaysMike** [comment]
I see that it does have trouble with serializing an XDocument. I'll work on XML serialization tonight and post an update once it's working.

**Comment by ameetj85** [comment]
Thank you Mike. Please let me know when the fix is ready for testing.

**Comment by replaysMike** [comment]
Hi @ameetj85 - let me know if version 1.0.42 solves your problem, it should be available on Nuget shortly. This was challenging to get working, I may take another stab at it when my schedule is less busy as I didn't like the solution I came up with, but it should be functional.

**Comment by ameetj85** [comment]
Hello Mike,
Thank you for the update. I am on vacation until Fri 12/28. I will let you know how this works after I return. Thanks again.
